// Course type definition matching actual Supabase database schema
export interface Course {
  id?: string // Auto-generated by Supabase
  title: string
  instructor: string
  description: string
  credits: number // Decimal credits (e.g. 1.5)
  credit_type: string // e.g. "General"
  modules: number
  selection: string // "Recommended", "Celebrity", "Continue", "top", "ai_web3"
  featured: boolean // For featured tag display
  new_tag: boolean // For new tag display  
  focus?: string // Text variable for later use
  image_link?: string // Not used currently
  
  // Frontend-only fields (not in database)
  progress?: number // User's progress (0-100)
  imageUrl?: string // Fallback image URL
  tags?: string[] // Derived from other fields
  level?: 'Beginner' | 'Intermediate' | 'Advanced' // Frontend categorization
  rating?: number // Mock rating for display
  studentsEnrolled?: number // Mock enrollment count
  duration?: string // Calculated from modules/credits
  createdAt?: string
  updatedAt?: string
}

// Learning Track type definition
export interface LearningTrack {
  id: string
  rank: string
  title: string
  instructor: string
  description: string
  courses: string[] // Array of course IDs
  totalCredits: number
  duration: string
}

// Legacy function to maintain compatibility - now fetches from Supabase
export function getCoursesbyCategory(category: string): Course[] {
  // This will be replaced by async API calls in components
  // Keeping for backwards compatibility during transition
  return []
}

// Export course categories for reference
export const COURSE_CATEGORIES = [
  'Recommended For You',
  'Continue Watching',
  'The Next Frontier: AI & Crypto',
  'Featured Courses',
  'New Releases',
  'Popular Now'
] as const

export type CourseCategory = typeof COURSE_CATEGORIES[number]

// Selection values used in database for filtering
export const COURSE_SELECTIONS = [
  'Recommended', // For "Recommended For You" section
  'Celebrity',   // Also for "Recommended For You" section
  'Continue',    // For "Continue Watching" section
  'top',         // For "Top 5 in Your Jurisdiction" section
  'ai_web3'      // For "The Next Frontier: AI & Crypto" section
] as const

export type CourseSelection = typeof COURSE_SELECTIONS[number]